# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: yohei.codes
email: 
description: >- # this means to ignore newlines until "baseurl:"
  I code. It might be good or bad.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://ykskb.github.io" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://yohei.codes" 
google_analytics: UA-52885755-2
twitter_username: yo__ohei
github_username:  ykskb
linkedin_username: yohei-kusakabe

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-polyglot

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Polyglot
languages: ["en", "jp"]
default_lang: "en"
exclude_from_localization: ["assets/css", "assets/img"]
parallel_localization: true

# Override global permalinks
collections:
  my_collection:
    output: true
    permalink: /:collection/:name